commands, config: tally and report unknown fields in config
Updates #628
Requires https://github.com/tendermint/tmlibs/pull/47 first

With new flag `--check-config`, we can now tally fields from
the config file mapped to Go struct by tag "mapstructure",
with those parsed out by viper and report an error if we
find flags/fields that aren't accepted in the config.

Note: We use the `--check-config` flag to maintain backward/forward
compatibility with different versions of the file, as raised
by @ebuchman at
https://github.com/tendermint/tendermint/pull/636#issuecomment-327011405

* Exhibit:
Given config in:
```shell
proxy_app = "tcp://127.0.0.1:46658"
moniker = "anonymous"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:46657"

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = ""
trex = "hey"
picked = "bonjour"
```

Running:
```shell
$ tendermint --home ~/.tendermint node --check-config
ERROR: We've detected these unknown flags in your config file
p2p:
  picked
  trex

```