fix protocol generate problem when using cpp
Because I want to build cpp application based on tendermint abci，so I use these protocol files to generate grpc and pb cpp files. But I meet these:
```
../../tendermint/consensus/types.pb.h:3659:57: error: return type of out-of-line definition of
      'tendermint::consensus::Message::has_vote' differs from that in the declaration
inline const ::tendermint::consensus::HasVote& Message::has_vote() const {
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~          ^
../../tendermint/consensus/types.pb.h:3553:22: note: previous definition is here
inline bool Message::has_vote() const {
```

`vote` and `has_vote` will cause function name conflict in pb.h file. So I solve this problem with this easy way.